name: mailer
version: 1.0.1
description: Compose and send emails from Dart. Supports file attachments, HTML emails and multiple transport methods.
authors:
- Kai Sellgren <kaisellgren@gmail.com>
- Dan Rubel <danrubel@google.com>
homepage: http://github.com/kaisellgren/mailer
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  unittest: '>=0.9.0 <2.0.0'
  mime: '>=0.9.0 <2.0.0'
  logging: '>=0.9.0 <2.0.0'
  crypto: '>=0.9.0 <2.0.0'
  path: '>=0.9.0 <2.0.0'
  intl: '>=0.9.0 <2.0.0'
