name: mailer
version: 5.0.0
description: >
  Compose and send emails from Dart.
  Supports file attachments and HTML emails
homepage: https://github.com/kaisellgren/mailer
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  async: '^2.5.0'
  logging: '^1.0.0'
  intl: '^0.17.0'
  mime: '^1.0.0'
  path: '^1.7.0'
  pedantic: '^1.9.2'
  meta: '^1.3.0'

dev_dependencies:
  args: '^2.0.0'
  test: '^1.5.1'
  googleapis_auth: '^1.0.0'
